[2025-07-27T09:00:52.788+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-27T09:00:52.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts manual__2025-07-27T09:00:40.955475+00:00 [queued]>
[2025-07-27T09:00:52.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.risk_alerts manual__2025-07-27T09:00:40.955475+00:00 [queued]>
[2025-07-27T09:00:52.843+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-27T09:00:52.857+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): risk_alerts> on 2025-07-27 09:00:40.955475+00:00
[2025-07-27T09:00:52.865+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2025-07-27T09:00:52.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'risk_alerts', 'manual__2025-07-27T09:00:40.955475+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmp2v1wwa06']
[2025-07-27T09:00:52.873+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask risk_alerts
[2025-07-27T09:00:52.901+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-27T09:00:52.949+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.risk_alerts manual__2025-07-27T09:00:40.955475+00:00 [running]> on host 9847cdb5c5e6
[2025-07-27T09:00:53.071+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team' AIRFLOW_CTX_DAG_ID='bank_data_pipeline' AIRFLOW_CTX_TASK_ID='risk_alerts' AIRFLOW_CTX_EXECUTION_DATE='2025-07-27T09:00:40.955475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-27T09:00:40.955475+00:00'
[2025-07-27T09:00:53.072+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-27T09:00:53.086+0000] {bank_data_pipeline.py:168} INFO - Starting risk alert checks for run manual__2025-07-27T09:00:40.955475+00:00
[2025-07-27T09:00:53.444+0000] {bank_data_pipeline.py:189} INFO - Risk alert checks passed: Risk violations: 39

[2025-07-27T09:00:53.444+0000] {bank_data_pipeline.py:190} INFO - Task completed successfully
[2025-07-27T09:00:53.444+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success', 'message': 'Risk alert checks passed'}
[2025-07-27T09:00:53.445+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-27T09:00:53.483+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bank_data_pipeline, task_id=risk_alerts, run_id=manual__2025-07-27T09:00:40.955475+00:00, execution_date=20250727T090040, start_date=20250727T090052, end_date=20250727T090053
[2025-07-27T09:00:53.523+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-27T09:00:53.579+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-27T09:00:53.585+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
